kaltura/playkit-js-ima-dai

src/ima-dai-engine-decorator.js
src/ima-dai.js

* Do not pause on ad click for live
* Load the engine synchronously (safari first play fix)

do not pause on ad click for live

---

src/assets/style.css
src/ima-dai.js

fix: css collision with ima plugin

---

src/ima-dai.js

the click event wasn't dispatched from the plugin.

fix(FEC-9048): click event is not dispatched

---

src/ima-dai.js

Do not remove non-exists child

fix(FEC-9075): resume ad from toolbar doesn't work

---

src/ima-dai-engine-decorator.js
src/ima-dai.js

* Ignore preroll when `startTime` configured
* Calculate the correct `startTime` including ads (depends on https://github.com/kaltura/kaltura-player-js/pull/240)

feat(FEC-9046,FEC-9087): start time support

---

src/ima-dai.js

Change every check of device.type to mobile or tablet instead, there are more device types which not relevant.

fix(FEC-9177): Smart TV showed as mobile device

---

package.json
src/ima-dai-ads-controller.js
src/ima-dai.js
yarn.lock

* `IAdsPluginController` implementing (`active`, `done` getters)
* change `ALL_ADS_COMPLETED` to `ADS_COMPLETED` (for multiple ads plugins support)
Dependes on https://github.com/kaltura/playkit-js/pull/350

feat(FEC-8631): bumper plugin

---

src/ima-dai-ads-controller.js

`ImaDAIAdsController` exposes `name`. 
See https://github.com/kaltura/playkit-js/pull/368

fix(FEC-9192): post bumper doesn't play

---

package.json
src/ima-dai-engine-decorator.js
src/ima-dai-event-manager.js
src/ima-dai.js
yarn.lock

update `ImaDAIEngineDecorator` according to https://github.com/kaltura/playkit-js/pull/369

feat(FEC-9145): support non sibling video tags

---

package.json
src/ima-dai.js
yarn.lock

add protocol to plugin for Samsung Smart TV bug

fix(FEC-9237): add app protocol for ima-dai plugin

---

src/ima-dai.js

**issue:** ima-dai sdk fires `AD_BREAK_START` once the play requested even it actually failed.
**solution:** fire `AD_BREAK_END` once get `PLAY_FAILED` and then listen to `FIRST_PLAY`
to re-fire `AD_BREAK_START`
Solves FEC-9515

fix(FEC-9515): the player gets stuck when autoplay is failed

---

docs/api.md
flow-typed/types/ima-dai-config.js
src/ima-dai.js

from all the ticket requests only authToken was missing.
playerType and playerVersion are not supported in IMA-DAI and the last two already exist in the code
solves FEC-9988

feat(FEC-9988): add missing IMA DAI Parameters to buildStreamRequest

---

.travis.yml

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

chore: change Jenkins ping version

---

src/ima-dai.js

Added catch and reject in getStreamUrl but more important added catch to _loadImaDAILib as the promise reject didn't bubble up

fix(FEC-10344): IMA DAI breaks playback when ad blocker is enabled

---

src/ima-dai.js

move startTime to the sources config so it will take place only on the a specific source.

feat(FEC-10686): move startTime config from playback to sources

---

docs/api.md
flow-typed/types/ima-dai-config.js
src/ima-dai.js

Add uiSetting for IMA DAI with locale config.

feat(FEC-10264): add support for IMA DAI UiSettings - locale

---

package.json
src/ima-dai-ads-controller.js
src/ima-dai.js
yarn.lock

remove the empty implementation and check for API in kaltura player.

fix(FEC-11062): ad layout doesn't work when IMA DAI configured

---

src/ima-dai.js
yarn.lock

Registration and accessing of services (previously known as managers) was moved from ui to KP
KP PR - kaltura/kaltura-player-js#477
UI PR - kaltura/playkit-js-ui#630
So changes needed to be updated also in ima-dai
solves FEC-11475

feat(FEC-11475): create service manager that allows registration and accessing of services

---

package.json

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

fix(FEC-12717): add timeline dependency to ima-dai plugin

---

package.json

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

fix(FEC-12847): set ima-dai correct name in dependencies FEC-12847
